#!/bin/bash

# Usage: ./run [-o <path>] [-h] [-v] [-x] [-c|r] <input>"
#  
# Shortcut script for running the compiler with the given arguments.
# 
# The output directory is by default set to ./output/ by sending "-o output/"
# to JPT.jar. This can be overridden with the -o option.
# 
# Options:
#   -o <path>   Set output directory to <path>
#   -v          Run the compiler in verbose mode.
#   -x          Deletes the output directory before compiling. Use with caution!
#   -c          Compile the generated java files from the pt-compiler, with Ant
#   -r          ... Then run it with java (not yet implemented)
#   -h          Show help for the run script.


outfolder="output/"
ptmode=
cleanfirst=


showusage() {
    sed -n 's/^# //; 3 p' $0
}

showinfo() {
    # Print line 3 through 7
    sed -n 's/^# //; 3,9 p' $0
}

showopts() {
    # Print line 8 through 15
    sed -n 's/^# //; 10,16 p' $0
}


# Parse options
args=`getopt o:vcrxh $*`
if test $? != 0
then
    echo
    showopts
    exit 1
fi

set -- $args
for i
do
    case "$i" in
        -v) shift; ptmode="$ptmode -v" ;;
        -o) shift; outfolder=$1 ; shift ;;
        -c) shift; thencompile=yesplease ;;
        -x) shift; cleanfirst=ifyousayso ;;
        -r) shift; echo "opt -r is not yet implemented." ;;
        -h) shift; shownhelp=yes ; showinfo ; showopts ;;
    esac
done

shift

# Ingen argumenter (bortsett fra evt opsjoner):
if [[ -z "$@" ]]
then
    if [[ -z "$shownhelp" ]]
    then
        echo Missing input folder!
        showusage

    fi

    exit
fi


# Kompilerer hvis ikke jar-fila finnes
if [[ ! -e build/jar/JPT.jar ]]
then
    ant jar
fi


# Clean
if [[ -n "$cleanfirst" ]] && [[ -e "$outfolder" ]]
then
    if [[ ! -d "$outfolder" ]]
    then
        echo "Don't wanna remove \"$outfolder\": not a directory!"
        exit 1
    fi

    echo "Removing $outfolder"
    rm -rf $outfolder
fi

# Kjør kompilator og evt kompiler output
java -jar build/jar/JPT.jar -o $outfolder $ptmode $@ && \

    if [[ -n "$thencompile" ]]
    then
        (cd $outfolder && ant)
    fi

